### ISSUE TITLE
iOS - Hero graphic taking up full screen in portrait mode

### ISSUE THREAD

**Issue by koulopoulos** [localtv/Issues#1]
See screenshot below. Hero graphic sizing in portrait mode makes viewing channels nearly impossible on iPhone 13 (iOS 15.6).

![portrait](https://github.com/localtv/Issues/assets/40676764/11da224d-8392-4d0c-b3fc-8d285939dd6b)

**Comment by anurodhp** [comment]
Will be fixed in the next public beta
