### ISSUE TITLE
tvOS Guide Navigation to/from Account Icon + Loading Indication

### ISSUE THREAD

**Issue by thechoppers** [localtv/Issues#2]
On Apple TV if the Account icon (upper right) is highlighted/selected, then scrolling left does nothing, and scrolling down dumps you several hours into the future on the guide instead of at the current time, which requires scrolling left.

Similarly, it is not possible to scroll up to the Account icon from the left side of the guide. Instead, must scroll right a few time blocks before being able to scroll up to the Account icon.

Also, only getting a spinning circle when loading a channel for the first time after launching the app. Subsequent channel changes load without displaying the spinning circle. Just inconsistent GUI.

**Comment by anurodhp** [comment]
Thanks, you make some very good points about the usability here. We are working on updating it for the next beta. will keep this open until thats done. 

What is the spinning you see when you view the channel? If possible could you share a picture of it?

**Comment by thechoppers** [comment]
![IMG_1484](https://github.com/localtv/Issues/assets/162375161/a288b305-10d9-492d-9250-55c7e8434637)

**Comment by anurodhp** [comment]
We are making updates in the next release to speed this up.
