### ISSUE TITLE
Location access error, app does not work.

### ISSUE THREAD

**Issue by Anonymous2Post** [localtv/Issues#3]
I’m receiving this error message “ Location Access Needed
We must check your location to determine legal access to these stations. Please allow location access for this app in Settings”. You do not need to check my location to determine legal access to the stations, I should be able to enter my ZIP Code in order for you to determine my location. This app does not work.

**Comment by anurodhp** [comment]
Location verification is mandatory.

**Comment by Anonymous2Post** [comment]
Why develop the app with location verification being mandatory? No reason that I cannot manually enter my zip code.

**Comment by Anonymous2Post** [comment]
> Location verification is mandatory.

Why develop the app with location verification being mandatory? No reason that I cannot manually enter my zip code.

**Comment by anurodhp** [comment]
Because if we don’t everyone in the world can just enter a Boston zip code to watch and the app will be shut down for piracy.
