### ISSUE TITLE
Only seeing a subset of channels

### ISSUE THREAD

**Issue by joe-goullaud** [localtv/Issues#4]
Currently only seeing PBS-WGBH, CBS-WBZ, ABC-WCVB, 7-WHDH, and CW-WLVI. What happened to NBC-WBTS and FOX-WFXT?

**Comment by anurodhp** [comment]
We had a server outage yesterday. Around that time it has just recovered and was downloading new guide data. I see ever channel now do you? I will make some adjustments to be more resilient to losing guide data though

**Comment by joe-goullaud** [comment]
Yup. They're all there now. Thanks!!
