### ISSUE TITLE
No audio when watching a channel through airplay to potentially a roku device

### ISSUE THREAD

**Issue by coolpro313** [localtv/Issues#8]
I tried watching a channel on saturday through my roku through airplay the video plays fine but completely no audio at all so i tried 5 other channels same thing video was fine just no audio at all the only time that there's audio is when i watch the channels either through my phone speakers or a headset and that's it but no audio when watching a channel through airplay not sure if same thing happens on other airplay compatible devices but it happens through roku

**Comment by anurodhp** [comment]
The issue appears to be that we send the original Dolby surround 5.1 audio (ac3) and depending on the Roku device  not all of them have a decoder for this. Some Rokus pass through the audio it seems so you need another device like a  receiver that can decode it

**Comment by anurodhp** [comment]
Switching to AC3 audio should have fixed this now

**Comment by coolpro313** [comment]
thx tried it and got audio with no issues just did it to help you out just like with any other small indie developers i like to help them out to expand their projects from small testflight rank to popular pro app store rank to get up to the charts so i'm doing this with you to help you out that's what i did with the app storyfire so i'm doing the same thing with your app where so far your app is great where with my own antenna i can't get much channels the worse channel that i get is metv toons strong enough for my antenna to add it to the found list but not enough for clear picture so with your app i can watch my favorite toons mostly clear depending on what's going on with foxboro's end but so far got audio and keep on improving the app I've got your back as a tester
